language: cpp
os:
- osx
compiler:
- clang
before_install:
- brew update
install:
- brew install qt5
- brew install libarchive
- brew link libarchive --force
- brew install xerces-c
- brew link xerces-c --force
before_script:
- export QMAKESPEC=macx-clang
- mkdir -p "$TRAVIS_BUILD_DIR-build"
- pushd "$TRAVIS_BUILD_DIR-build"
- QMAKE=`find /usr/local -name "qmake" | head -n 1`
- DEPLOY=`find /usr/local -name "macdeployqt" | head -n 1`
- $QMAKE -v
- echo "compile release version only"
- $QMAKE -r -Wall -Wlogic -Wparser CONFIG+=release "$TRAVIS_BUILD_DIR"
- popd
script:
- DEPLOY=`find /usr/local -name "macdeployqt" | head -n 1`
- make -C "$TRAVIS_BUILD_DIR-build" -j2 all
- pushd "$TRAVIS_BUILD_DIR-build"
- pwd
- ls -la
- $DEPLOY MAPster.app -no-strip -verbose=3
- popd
- pwd
- ls -la
- cp -f -R "$TRAVIS_BUILD_DIR/configs/" "$TRAVIS_BUILD_DIR-build/MAPster.app/Contents/MacOS/configs"
- cp -f -R "$TRAVIS_BUILD_DIR/Info.plist" "$TRAVIS_BUILD_DIR-build/MAPster.app/Contents/Info.plist"
- make -C "$TRAVIS_BUILD_DIR-build" -j2 all
- pushd "$TRAVIS_BUILD_DIR-build"
- pwd
- ls -la
- $DEPLOY MAPster.app -no-strip -dmg -verbose=3
- du -s -h MAPster.app.dmg
