language: cpp

compiler: clang

before_install:
 - sudo apt-get install libarchive-dev
 - sudo apt-get install libxerces-c-dev
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
script:
 - qmake -project
 - qmake MAPster.pro
 - make
