language: cpp

compiler: clang

before_install:
 - sudo apt-get install libarchive-dev
 - sudo apt-get install libxerces-c-dev
 - sudo apt-get update -qq
 - sudo apt-get install -qq sqlite3 qt5-dev-tools

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
 - qmake -project
 - qmake MAPster.pro
 - make
