language: cpp
os:
 - osx
compiler:
 - clang
before_install:
 - brew update
install:
 - brew install homebrew/versions/qt5
 - brew install libarchive
 - brew link libarchive
 - brew install xerces-c
 - brew link xerces-c
before_script:
 - export QMAKESPEC=macx-clang
 - mkdir -p "$TRAVIS_BUILD_DIR-build"
 - pushd "$TRAVIS_BUILD_DIR-build"
 - QMAKE=`find /usr/local -name "qmake" | head -n 1`
 - DEPLOY=`find /usr/local -name "macdeployqt" | head -n 1`
 - "$QMAKE -v"
 - echo "compile release version only"
 - $QMAKE -r -Wall -Wlogic -Wparser CONFIG+=release "$TRAVIS_BUILD_DIR"
 - popd
script:
 - make -C "$TRAVIS_BUILD_DIR-build" -j2 all
 - pushd "$TRAVIS_BUILD_DIR-build"
 - pwd
 - ls -la
 - DEPLOY=`find /usr/local -name "macdeployqt" | head -n 1`
 - "$DEPLOY MAPster.app -no-strip -dmg -verbose=3"
 - du -s -h MAPster_macOS_beta2.4.dmg
